#!/usr/bin/env node
/**
 * generate-readme — render the README tool tables from the tool manifest.
 *
 * The manifest (`src/tools/index.ts`) is the single source of truth for the tool
 * surface; a README table maintained by hand is a second copy of it, and a
 * second copy drifts. This script reads the BUILT manifest and rewrites
 * everything between the `GENERATED:TOOLS` markers in README.md.
 *
 * Usage:
 *   node scripts/generate-readme.mjs            rewrite README.md in place
 *   node scripts/generate-readme.mjs --check    exit 1 if README.md is stale
 *
 * `--check` is what the drift test runs. It never writes, so it is safe in CI.
 *
 * Requires `npm run build` first: reading the manifest from `build/` rather than
 * parsing the TypeScript keeps this script free of a compiler dependency and
 * means it sees exactly the values the server will register.
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const README_PATH = resolve(REPO_ROOT, 'README.md');
const MANIFEST_PATH = resolve(REPO_ROOT, 'build/tools/index.js');

const START = '<!-- GENERATED:TOOLS:START -->';
const END = '<!-- GENERATED:TOOLS:END -->';

/** The command a failing check should tell the reader to run. */
export const REGENERATE_COMMAND = 'npm run readme';

// ---------------------------------------------------------------------------
// Rendering
// ---------------------------------------------------------------------------

/** Roughly one line of table cell; sentences are taken whole up to this. */
const SUMMARY_TARGET = 110;
const SUMMARY_MAX = 200;

/**
 * The opening sentences of a tool description, for the table's last column.
 *
 * Tool descriptions are written for the model and run several sentences; a table
 * cell that long is unreadable, and docs/TOOLS.md already holds the full text.
 * One sentence alone is sometimes too little ("Create one issue."), so sentences
 * are taken whole until the cell is about a line long — never cut mid-sentence,
 * because a truncated instruction reads as a complete but wrong one.
 */
function summarize(text) {
  const flat = text.replace(/\s+/gu, ' ').trim();
  // Split only where a terminator is FOLLOWED by whitespace: `data.nextPageToken`
  // and `e.g.` keep their dots, which a naive `[^.!?]+[.!?]` splitter loses.
  const sentences = flat.split(/(?<=[.!?])\s+/u);

  const taken = [];
  let length = 0;
  for (const sentence of sentences) {
    const next = length === 0 ? sentence.length : length + 1 + sentence.length;
    if (taken.length > 0 && next > SUMMARY_MAX) break;
    taken.push(sentence);
    length = next;
    if (length >= SUMMARY_TARGET) break;
  }

  const summary = taken.join(' ');
  return summary.length > SUMMARY_MAX
    ? `${summary.slice(0, SUMMARY_MAX - 1).trimEnd()}…`
    : summary;
}

/** Markdown table cells cannot contain a raw pipe or a line break. */
function cell(text) {
  return text.replace(/\s+/gu, ' ').replaceAll('|', '\\|').trim();
}

/** What a caller most needs to know before calling: may this change anything? */
function access(tool) {
  if (tool.annotations.readOnlyHint) return 'read-only';
  return tool.writeTier === 'irreversible' ? 'write · irreversible' : 'write · standard';
}

function renderPackage(pkg) {
  const rows = pkg.tools.map(
    (tool) =>
      `| \`${tool.name}\` | ${cell(tool.title)} | ${access(tool)} | ${cell(
        summarize(tool.description),
      )} |`,
  );

  return [
    `### ${cell(pkg.title)} — \`${pkg.id}\``,
    '',
    cell(pkg.description),
    '',
    '| Tool | Title | Access | What it does |',
    '| --- | --- | --- | --- |',
    ...rows,
    '',
  ].join('\n');
}

/**
 * The whole generated block, marker to marker.
 *
 * Written as prose plus tables rather than one flat list because the package is
 * the unit a reader configures: `JIRA_TOOL_PACKAGES` turns these headings on and
 * off, and a table that ignored them would not answer "what do I lose if I only
 * enable `core` and `search`?".
 */
export function renderTools(packages) {
  const toolCount = packages.reduce((sum, pkg) => sum + pkg.tools.length, 0);
  const writeCount = packages.reduce(
    (sum, pkg) => sum + pkg.tools.filter((tool) => !tool.annotations.readOnlyHint).length,
    0,
  );

  return [
    START,
    '',
    '<!-- Generated by scripts/generate-readme.mjs from the tool manifest.',
    `     Do not edit by hand — run \`${REGENERATE_COMMAND}\`. -->`,
    '',
    `${toolCount} tools in ${packages.length} packages, ${writeCount} of them write tools`,
    'behind the plan/apply gate. `JIRA_TOOL_PACKAGES`, `JIRA_PACKAGES_DENY` and',
    '`JIRA_PACKAGES_READONLY` decide which of them a session actually sees; the',
    '`core` package is always registered. Full input and output shapes are in',
    '[`docs/TOOLS.md`](docs/TOOLS.md).',
    '',
    ...packages.map(renderPackage),
    END,
  ].join('\n');
}

/** Splice the generated block into an existing README. */
export function spliceReadme(readme, block) {
  const start = readme.indexOf(START);
  const end = readme.indexOf(END);
  if (start === -1 || end === -1 || end < start) {
    throw new Error(
      `README.md is missing the ${START} / ${END} markers; restore them before generating.`,
    );
  }
  return readme.slice(0, start) + block + readme.slice(end + END.length);
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

async function loadPackages() {
  if (!existsSync(MANIFEST_PATH)) {
    throw new Error(
      `The built manifest ${MANIFEST_PATH} does not exist. Run \`npm run build\` first.`,
    );
  }
  const module = await import(pathToFileURL(MANIFEST_PATH).href);
  return module.PACKAGES;
}

async function run(argv) {
  const check = argv.includes('--check');
  const packages = await loadPackages();
  const current = readFileSync(README_PATH, 'utf8');
  const next = spliceReadme(current, renderTools(packages));

  if (next === current) {
    if (!check) process.stderr.write('README.md is already up to date.\n');
    return 0;
  }

  if (check) {
    process.stderr.write(
      `README.md is out of date with the tool manifest. Regenerate it with: ${REGENERATE_COMMAND}\n`,
    );
    return 1;
  }

  writeFileSync(README_PATH, next, 'utf8');
  process.stderr.write('README.md tool tables regenerated.\n');
  return 0;
}

// Only when invoked directly — the drift test imports nothing from here, but a
// future consumer should not trigger a rewrite by importing this module.
if (
  process.argv[1] !== undefined &&
  resolve(process.argv[1]) === fileURLToPath(import.meta.url)
) {
  run(process.argv.slice(2)).then(
    (code) => {
      process.exitCode = code;
    },
    (error) => {
      process.stderr.write(
        `generate-readme: ${error instanceof Error ? error.message : String(error)}\n`,
      );
      process.exitCode = 1;
    },
  );
}
