#!/usr/bin/env node
/**
 * rehearse-live — run the Gate C driver end to end against a fake Jira.
 *
 * Gate C is expensive: the owner has to provision a scratch Jira Cloud site,
 * seed it, and babysit a run. Every bug in `scripts/verify-live.mjs` that only
 * shows up on the wire costs one of those round trips. This script makes the
 * first live run boring by running the *whole* driver — the same
 * `verify-live.mjs`, spawning the same `build/index.js`, over the same stdio
 * transport — against `scripts/fake-jira.mjs` instead of Atlassian.
 *
 * WHAT THIS PROVES, AND WHAT IT DOES NOT. It proves things about the DRIVER and
 * about the SERVER'S PLUMBING: that every claim's tool arguments satisfy the
 * tool schemas, that the claims sequence correctly, that the write gate behaves,
 * that paging terminates, that a 429 is retried and an unsafe write is not, that
 * no credential reaches the media host, that the report and exit codes are what
 * the runbook says. It proves NOTHING about Jira. Where the fake had to take a
 * position on a wire detail that only Atlassian can settle, `fake-jira.mjs` says
 * so at the route and `docs/RELEASING.md` §6 lists it as still needing Gate C. A
 * green rehearsal is a statement about our code, never about theirs.
 *
 * HOW IT REACHES THE FAKE WITHOUT WEAKENING ANYTHING. The server refuses
 * loopback by construction: `core/http.ts` applies the SSRF blocklist BEFORE the
 * allowlist, so `127.0.0.1`, `*.localhost`, `*.local` and `*.internal` are
 * unreachable no matter what `JIRA_ALLOWED_HOSTS` says — as they should be.
 * Rather than punch a hole in that, the fake answers to two ordinary DNS names,
 * `jira.rehearsal.test` and `media.rehearsal.test`, which are neither blocked
 * nor canonical, and which reach the fake only because:
 *
 *   - they are allowlisted through the supported `JIRA_ALLOWED_HOSTS` path;
 *   - `dns.lookup` is patched to `127.0.0.1` for exactly those two names,
 *     inside the spawned child only, via a `--import` preload;
 *   - the fake's self-signed cert is trusted through `NODE_EXTRA_CA_CERTS`.
 *
 * No source file changes, no test-only branch in `src/`, no relaxed host rule.
 * A build with the blocklist removed would still fail this rehearsal's
 * assertions the same way — the DNS patch is scoped to the child process and
 * cannot be reached from a normal run.
 *
 * Usage:
 *   node scripts/rehearse-live.mjs             # every pass
 *   node scripts/rehearse-live.mjs --pass A    # one pass
 *   node scripts/rehearse-live.mjs --keep      # keep the workdir for forensics
 *   node scripts/rehearse-live.mjs --verbose   # stream the driver's own output
 *
 * Exit codes: 0 = every pass met its expectations, 1 = something regressed,
 * 2 = setup error (no build, no openssl).
 */

import { spawn } from 'node:child_process';
import { existsSync } from 'node:fs';
import { mkdir, mkdtemp, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { parseArgs } from 'node:util';

import { API_HOST, MEDIA_HOST, startFakeJira } from './fake-jira.mjs';

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const DRIVER = join(REPO_ROOT, 'scripts', 'verify-live.mjs');
const SERVER_ENTRY = join(REPO_ROOT, 'build', 'index.js');

const EXIT_OK = 0;
const EXIT_FAILURE = 1;
const EXIT_CONFIG = 2;

/** A whole pass gets longer than one call: four child servers, ~30 claims. */
const PASS_TIMEOUT_MS = 300_000;

const EMAIL = 'rehearsal@example.invalid';
const TOKEN = 'rehearsal-token-not-a-real-secret';
const PROJECT = 'SCRATCH';
const PROJECT2 = 'LEGACY';

// ---------------------------------------------------------------------------
// The DNS preload
// ---------------------------------------------------------------------------

/**
 * Written into the workdir and injected with `--import` so that it applies to
 * `verify-live.mjs` AND to the server it spawns. Undici (Node's fetch) resolves
 * through `dns.lookup`, so patching it is enough; nothing else about the request
 * changes — the SNI, the Host header and the certificate check all still say
 * `jira.rehearsal.test`, which is exactly the point. If the server ever grew a
 * second network path that bypassed `dns.lookup`, this rehearsal would start
 * failing rather than silently passing.
 */
const PRELOAD_SOURCE = `// Generated by scripts/rehearse-live.mjs. Child-process only.
import dns from 'node:dns';

const HOSTS = new Set(${JSON.stringify([API_HOST, MEDIA_HOST])});
const ADDRESS = '127.0.0.1';
const FAMILY = 4;

const realLookup = dns.lookup;
dns.lookup = function lookup(hostname, options, callback) {
  if (!HOSTS.has(hostname)) return realLookup.call(this, hostname, options, callback);
  const done = typeof options === 'function' ? options : callback;
  const opts =
    typeof options === 'function'
      ? {}
      : typeof options === 'number'
        ? { family: options }
        : (options ?? {});
  queueMicrotask(() => {
    if (opts.all === true) done(null, [{ address: ADDRESS, family: FAMILY }]);
    else done(null, ADDRESS, FAMILY);
  });
  return undefined;
};

const realPromised = dns.promises.lookup;
dns.promises.lookup = async function lookup(hostname, options) {
  if (!HOSTS.has(hostname)) return realPromised.call(this, hostname, options);
  const opts = typeof options === 'number' ? { family: options } : (options ?? {});
  return opts.all === true
    ? [{ address: ADDRESS, family: FAMILY }]
    : { address: ADDRESS, family: FAMILY };
};
`;

// ---------------------------------------------------------------------------
// Passes
// ---------------------------------------------------------------------------

/**
 * @typedef {object} Pass
 * @property {string} id
 * @property {string} title
 * @property {string[]} args        Flags handed to verify-live.mjs.
 * @property {string[][]} [pre]     Driver runs to make first; their requests are
 *                                  discarded, so `check` only ever sees the
 *                                  measured run. Used to set up residue.
 * @property {object} [fake]        Extra options for startFakeJira.
 * @property {object[]} [faults]    Armed before the driver starts.
 * @property {boolean} [record]     Run with --record and audit the capture.
 * @property {number} [expectExit]  Expected process exit code.
 * @property {false | string} [confirm]  Override --confirm-site: `false` omits it,
 *                                  a string passes that host. Default: the fake's
 *                                  host, so a destructive pass is confirmed.
 * @property {(ctx: object) => string[]} [check]  Extra assertions; returns failures.
 */

/**
 * Invariants that hold in every pass, however the fake is configured. These are
 * the ones worth failing loudly: a route the fake does not implement means the
 * rehearsal silently skipped part of the wire, and a credential on the media
 * host is a real leak — Atlassian's media domain is a different origin, and the
 * whole point of the 303 hop is that the second request is unauthenticated.
 */
function universalChecks({ requests }) {
  const failures = [];
  const unmatched = requests.filter((r) => r.unmatched === true);
  if (unmatched.length > 0) {
    const names = [...new Set(unmatched.map((r) => `${r.method} ${r.path}`))];
    failures.push(`fake has no route for: ${names.join(', ')}`);
  }
  const leaked = requests.filter((r) => r.onMediaHost && r.hasAuthorization);
  if (leaked.length > 0) {
    failures.push(`credentials sent to the media host ${String(leaked.length)}x`);
  }
  const violations = requests.filter((r) => r.violation !== undefined);
  if (violations.length > 0) {
    failures.push(
      `fake flagged: ${[...new Set(violations.map((r) => r.violation))].join(', ')}`,
    );
  }
  const unauthenticated = requests.filter((r) => r.authFailure !== undefined);
  if (unauthenticated.length > 0) {
    failures.push(
      `the client failed authentication: ${[
        ...new Set(unauthenticated.map((r) => r.authFailure)),
      ].join(', ')}`,
    );
  }
  const broke = requests.filter((r) => r.handlerError !== undefined);
  if (broke.length > 0) {
    failures.push(
      `fake handler threw on ${broke.length} request(s): ${broke[0].handlerError}`,
    );
  }
  return failures;
}

/**
 * The agile write surface, asserted from the wire and from the fake's state
 * rather than only from the driver's own verdicts.
 *
 * A claim that says PASS proves the driver was satisfied; these checks prove
 * what actually reached the fake. The distinction matters most for the two
 * details a live tenant will judge us on: `originBoardId` must go out as a
 * NUMBER, and the sprint lifecycle must be driven with POST (partial update),
 * never PUT — Jira's PUT nulls every field the body omits, which would silently
 * wipe a real sprint's goal and dates.
 */
function agileWriteChecks({ requests, claims, state }) {
  const failures = [];
  const agile = (method, re) =>
    requests.filter((r) => r.method === method && re.test(r.path));

  const creates = agile('POST', /^\/rest\/agile\/1\.0\/sprint$/);
  if (creates.length !== 1) {
    failures.push(`expected exactly 1 POST /agile/sprint, saw ${String(creates.length)}`);
  } else {
    const create = creates[0];
    if (create.status !== 201) {
      failures.push(`sprint create answered ${String(create.status)}, expected 201`);
    }
    if (typeof create.body?.originBoardId !== 'number') {
      failures.push(
        `originBoardId went on the wire as ${typeof create.body?.originBoardId}, ` +
          'expected a number (the agile twin of the POST /version projectId trap)',
      );
    }
  }

  if (agile('POST', /^\/rest\/agile\/1\.0\/sprint\/\d+\/issue$/).length === 0) {
    failures.push('no issue was moved into a sprint');
  }
  if (agile('POST', /^\/rest\/agile\/1\.0\/backlog\/issue$/).length === 0) {
    failures.push('no issue was moved back to the backlog');
  }

  const lifecycle = agile('POST', /^\/rest\/agile\/1\.0\/sprint\/\d+$/);
  const states = lifecycle.map((r) => r.body?.state);
  if (!states.includes('active')) failures.push('the sprint was never started');
  if (!states.includes('closed')) failures.push('the sprint was never closed');
  if (agile('PUT', /^\/rest\/agile\/1\.0\/sprint\//).length > 0) {
    failures.push(
      'a sprint update used PUT — Jira PUT is a FULL update and nulls omitted fields',
    );
  }

  // The fake's own view: the sprint the driver made really is closed, and it is
  // still there, because nothing can delete it.
  const created = state.sprints.filter((sprint) => /^gate-c-/.test(sprint.name));
  if (created.length !== 1) {
    failures.push(`expected 1 gate-c sprint on the fake, saw ${String(created.length)}`);
  } else if (created[0].state !== 'closed') {
    failures.push(`the gate-c sprint ended in state ${String(created[0].state)}`);
  }

  for (const id of ['C27', 'C28', 'C29', 'C30']) {
    const row = claims.find((c) => c.id === id);
    if (row === undefined) failures.push(`${id} did not run`);
    else if (row.status !== 'PASS') failures.push(`${id} is ${row.status}: ${row.note}`);
  }
  // C27's note is the only place a reader is told the sprint is permanent.
  const c27 = claims.find((c) => c.id === 'C27');
  if (c27 !== undefined && !/DELETE A SPRINT/.test(c27.note)) {
    failures.push('C27 stopped saying that the sprint it creates cannot be deleted');
  }
  return failures;
}

/**
 * The residue tail, which every invocation now runs (C32).
 *
 * The inventory is the operator's only honest answer to "what did that just
 * leave on my site", so a pass that stops producing it is a regression even when
 * every other claim is green.
 */
function residueChecks({ claims, stderr }, expected = {}) {
  const failures = [];
  const c32 = claims.find((c) => c.id === 'C32');
  if (c32 === undefined) failures.push('C32 did not run — the run left no inventory');
  else if (c32.status !== 'PASS') failures.push(`C32 is ${c32.status}: ${c32.note}`);
  else {
    for (const [kind, count] of Object.entries(expected)) {
      if (!new RegExp(`\\b${kind}=${String(count)}\\b`).test(c32.note)) {
        failures.push(`C32 should report ${kind}=${String(count)}, said: ${c32.note}`);
      }
    }
  }
  // The inventory is printed on stderr, where diagnostics belong — stdout is
  // the claim report. Both halves matter: an operator reads the rendering, and
  // an empty class has to say so rather than vanish.
  if (!stderr.includes('Residue — what this gate can still see on the site')) {
    failures.push('the residue table was never rendered');
  }
  for (const title of [
    'throwaway issues',
    'project versions',
    'project components',
    'sprints',
    'local files in JIRA_MEDIA_DIR',
  ]) {
    if (!stderr.includes(title)) failures.push(`the residue table omits "${title}"`);
  }
  return failures;
}

/** Every agile write claim SKIPped, with nothing having reached the wire. */
function agileWriteSkipped(claims, why) {
  const failures = [];
  for (const id of ['C27', 'C28', 'C29', 'C30']) {
    const row = claims.find((c) => c.id === id);
    if (row === undefined) failures.push(`${id} did not run`);
    else if (row.status !== 'SKIP') {
      failures.push(`${id} should SKIP ${why}, got ${row.status}: ${row.note}`);
    }
  }
  return failures;
}

/** @type {Pass[]} */
const PASSES = [
  {
    id: 'A',
    title: 'full run — reads, writes and the delete phase',
    args: ['--write', '--irreversible'],
    record: true,
    expectExit: EXIT_OK,
    check: ({ requests, claims, state, stderr }) => {
      const failures = [];
      // Rule 3 in the driver's own header: writes touch only what it created.
      const wrote = requests.filter(
        (r) => ['POST', 'PUT', 'DELETE'].includes(r.method) && r.status < 300,
      );
      if (wrote.length === 0) failures.push('--write ran but no write reached the fake');
      // Rule 4: the delete phase must actually delete the throwaway issue.
      const deleted = requests.some(
        (r) => r.method === 'DELETE' && /^\/rest\/api\/3\/issue\/[^/]+$/.test(r.path),
      );
      if (!deleted)
        failures.push('--irreversible ran but no issue DELETE reached the fake');
      // A full run is every claim the driver owns. The exact number is asserted
      // rather than a floor, so adding a claim without teaching the fake the
      // routes it needs is caught here instead of on a live tenant.
      if (claims.length !== 41) {
        failures.push(`expected 41 claims in the report, saw ${String(claims.length)}`);
      }
      const c00 = claims.find((c) => c.id === 'C00');
      if (c00 === undefined) failures.push('C00 did not run — no doctor preflight');
      else if (c00.status !== 'PASS') failures.push(`C00 is ${c00.status}: ${c00.note}`);
      const c31 = claims.find((c) => c.id === 'C31');
      if (c31 === undefined) failures.push('C31 did not run — --project2 is dead again');
      else if (c31.status !== 'PASS') failures.push(`C31 is ${c31.status}: ${c31.note}`);
      failures.push(...agileWriteChecks({ requests, claims, state }));
      // A full run deletes both its issues but CANNOT delete the version, the
      // sprint or the component (D73), and it leaves the file it staged for the
      // upload. Those four numbers are the gate's residue contract; if any of
      // them moves, the runbook is lying to the owner.
      failures.push(
        ...residueChecks(
          { claims, stderr },
          { issues: 0, versions: 1, components: 1, sprints: 1, media: 1 },
        ),
      );
      // Recorded, not incidental: with the fake behaving the way real Jira
      // behaves (`redirect=false` answered with 200 and the bytes), the media
      // host is never contacted. C13 is named accordingly; pass B is the only
      // place the redirect branch runs.
      if (requests.some((r) => r.onMediaHost)) {
        failures.push('a media-host request happened without the redirect forced');
      }
      return failures;
    },
  },
  {
    id: 'B',
    title: 'reads with the 303 media redirect forced on',
    args: [],
    fake: { mediaMode: 'always' },
    expectExit: EXIT_OK,
    check: ({ requests, claims }) => {
      const failures = [];
      const hop = requests.filter((r) => r.onMediaHost);
      if (hop.length === 0) {
        failures.push('media redirect forced but no request reached the media host');
      }
      if (hop.some((r) => r.hasAuthorization)) {
        failures.push('Authorization header followed the 303 onto the media host');
      }
      if (hop.some((r) => r.violation !== undefined)) {
        failures.push('the fake flagged a violation on the media host');
      }
      const c13 = claims.find((c) => c.id === 'C13');
      if (c13 !== undefined && c13.status === 'FAIL') {
        failures.push(`C13 failed with the redirect forced: ${c13.note}`);
      }
      return failures;
    },
  },
  {
    id: 'C',
    title: 'reads with a 429 and a 503 injected',
    // `--skip-doctor`: the preflight probes GET /myself, so it would swallow the
    // injected 503 before the read phase ever saw it, and this pass would then
    // assert the retry against the wrong request. Pass A covers C00.
    args: ['--skip-doctor'],
    faults: [
      { method: 'GET', path: '/rest/api/3/myself', status: 503, times: 1 },
      {
        method: 'GET',
        path: '/rest/api/3/field',
        status: 429,
        headers: { 'retry-after': '1' },
        times: 1,
      },
    ],
    expectExit: EXIT_OK,
    check: ({ requests, claims }) => {
      const failures = [];
      const myself = requests.filter(
        (r) => r.method === 'GET' && r.path === '/rest/api/3/myself',
      );
      if (myself.length < 2) {
        failures.push('a 503 on GET /myself was not retried (safe methods must be)');
      }
      const field = requests.filter(
        (r) => r.method === 'GET' && r.path === '/rest/api/3/field',
      );
      if (field.length < 2) failures.push('a 429 on GET /field was not retried');
      for (const id of ['C03', 'C09']) {
        const row = claims.find((c) => c.id === id);
        if (row !== undefined && row.status === 'FAIL') {
          failures.push(`${id} failed under injected faults: ${row.note}`);
        }
      }
      return failures;
    },
  },
  {
    id: 'D',
    title: 'an unsafe write must not be replayed',
    args: ['--write'],
    faults: [{ method: 'POST', path: '/rest/api/3/issue', status: 503, times: 3 }],
    // C17 is expected to FAIL here: the create is meant to be refused, not retried.
    expectExit: EXIT_FAILURE,
    check: ({ requests, claims }) => {
      const failures = [];
      const creates = requests.filter(
        (r) => r.method === 'POST' && r.path === '/rest/api/3/issue',
      );
      if (creates.length === 0) failures.push('no issue create reached the fake at all');
      if (creates.length > 1) {
        failures.push(
          `an unsafe POST /issue was replayed ${String(creates.length)}x after a 503 — ` +
            'on a live site that is a duplicate issue',
        );
      }
      const c17 = claims.find((c) => c.id === 'C17');
      if (c17 !== undefined && c17.status !== 'FAIL') {
        failures.push(`C17 should FAIL when the create 503s, got ${c17.status}`);
      }
      return failures;
    },
  },
  {
    id: 'E',
    title: 'watcher roster withheld (CC-47) — the likely token permission',
    args: ['--write'],
    // A scratch site's token very often lacks "view voters and watchers". Jira
    // does not 403 for that: it returns 200 with the roster simply absent. C21
    // has a branch for it; without this pass that branch never runs before the
    // gate, and it is the branch most likely to run ON the gate.
    fake: { hideWatcherRoster: true },
    expectExit: EXIT_OK,
    check: ({ requests, claims, state }) => {
      const failures = [];
      const c21 = claims.find((c) => c.id === 'C21');
      if (c21 === undefined) failures.push('C21 did not run');
      else if (c21.status !== 'PASS') {
        failures.push(
          `C21 must degrade, not fail, when the roster is withheld: ${c21.note}`,
        );
      } else if (!c21.note.includes('withheld')) {
        failures.push(
          `C21 passed but did not report the roster as withheld: ${c21.note}`,
        );
      }
      // A withheld roster is a collab-surface permission and has nothing to do
      // with agile. Asserted anyway: a degradation branch that accidentally
      // takes other claims down with it is exactly the kind of coupling the
      // gate should not discover on a live tenant.
      failures.push(...agileWriteChecks({ requests, claims, state }));
      return failures;
    },
  },
  {
    id: 'F',
    title: 'no Jira Software licence (CC-34) — the agile surface 403s',
    // `--write` on purpose: the licence check has to cover the agile WRITES too,
    // and they only run in the write phase. Without it, C27–C30 would never be
    // exercised under the degradation this pass exists to simulate.
    args: ['--write'],
    // A brand-new scratch site is very often Jira Work Management only, so every
    // /rest/agile/1.0 call 403s. `times` is high enough to cover the whole run.
    faults: [{ path: '/rest/agile/1.0/board', status: 403, times: 20 }],
    // A missing licence is a property of the site, not a defect in the code, so
    // the gate's evidence must not show it as red.
    expectExit: EXIT_OK,
    check: ({ requests, claims, stderr }) => {
      const failures = [];
      // The residue table's blind spot, end to end: with the agile root 403ing,
      // the inventory cannot enumerate sprints, and printing `sprints: none`
      // there would tell the operator the site is clean when nobody looked.
      if (!/sprints: UNKNOWN/.test(stderr)) {
        failures.push('the residue table did not mark sprints as unread');
      }
      if (/\bsprints: none\b/.test(stderr)) {
        failures.push('the residue table called an unreadable class clean');
      }
      const c11 = claims.find((c) => c.id === 'C11');
      if (c11 === undefined) failures.push('C11 did not run');
      else if (c11.status !== 'SKIP') {
        failures.push(
          `C11 should SKIP when the site has no Jira Software, got ${c11.status}`,
        );
      }
      failures.push(...agileWriteSkipped(claims, 'without a Jira Software licence'));
      // The board probe is the gate: nothing else on the agile root may be
      // attempted once it 403s, or a live run would pile up permission errors.
      const beyondProbe = requests.filter(
        (r) =>
          r.path.startsWith('/rest/agile/1.0/') && r.path !== '/rest/agile/1.0/board',
      );
      if (beyondProbe.length > 0) {
        failures.push(
          `${String(beyondProbe.length)} agile call(s) went out after the 403 probe: ` +
            [...new Set(beyondProbe.map((r) => `${r.method} ${r.path}`))].join(', '),
        );
      }
      return failures;
    },
  },
  {
    id: 'G',
    title: 'the board already has an active sprint — the start is refused',
    args: ['--write'],
    // The other agile degradation, and the one most likely on a real scratch
    // site: a Scrum board created from a template ships WITH an active sprint,
    // and Jira refuses a second one unless parallel sprints are enabled. That is
    // an HTTP 400, so the naive driver would report it as a red claim for
    // something that is site configuration, not a defect.
    fake: { boardHasActiveSprint: true },
    expectExit: EXIT_OK,
    check: ({ requests, claims, state }) => {
      const failures = [];
      // The create still has to work — only the start is refused.
      for (const id of ['C27', 'C28']) {
        const row = claims.find((c) => c.id === id);
        if (row === undefined) failures.push(`${id} did not run`);
        else if (row.status !== 'PASS')
          failures.push(`${id} is ${row.status}: ${row.note}`);
      }
      const c29 = claims.find((c) => c.id === 'C29');
      if (c29 === undefined) failures.push('C29 did not run');
      else if (c29.status !== 'SKIP') {
        failures.push(
          `C29 should SKIP when the board refuses a second sprint, got ${c29.status}`,
        );
      } else if (!/parallel sprints|already has an active sprint/i.test(c29.note)) {
        failures.push(`C29 skipped without quoting why Jira refused: ${c29.note}`);
      }
      const c30 = claims.find((c) => c.id === 'C30');
      if (c30 === undefined) failures.push('C30 did not run');
      else if (c30.status !== 'SKIP') {
        failures.push(`C30 should SKIP when the sprint never started, got ${c30.status}`);
      }
      // A refused start must not have been retried: it is an unsafe write.
      const starts = requests.filter(
        (r) =>
          r.method === 'POST' &&
          /^\/rest\/agile\/1\.0\/sprint\/\d+$/.test(r.path) &&
          r.body?.state === 'active',
      );
      if (starts.length !== 1) {
        failures.push(
          `the refused start was sent ${String(starts.length)}x, expected once`,
        );
      }
      const stranded = state.sprints.filter((sprint) => /^gate-c-/.test(sprint.name));
      if (stranded.length === 1 && stranded[0].state !== 'future') {
        failures.push(
          `the sprint should still be future, it is ${String(stranded[0].state)}`,
        );
      }
      return failures;
    },
  },
  {
    id: 'H',
    title: 'residue inventory finds what an interrupted run left behind',
    // The pre-run keeps its issue — the shape of a gate that was Ctrl-C'd, or
    // that failed half way. The measured run is the READ-ONLY inventory, which
    // is what an operator types when they want to know what is on their site.
    pre: [['--write', '--keep']],
    args: ['--residue'],
    expectExit: EXIT_OK,
    check: ({ requests, claims, stderr }) => {
      const failures = [];
      failures.push(
        ...residueChecks(
          { claims, stderr },
          { issues: 2, versions: 1, components: 1, sprints: 1, media: 1 },
        ),
      );
      // Read-only means read-only: --residue without --purge must not mutate.
      const wrote = requests.filter((r) => ['POST', 'PUT', 'DELETE'].includes(r.method));
      const mutating = wrote.filter((r) => r.path !== '/rest/api/3/search/jql');
      if (mutating.length > 0) {
        failures.push(
          `--residue wrote to the site: ${[
            ...new Set(mutating.map((r) => `${r.method} ${r.path}`)),
          ].join(', ')}`,
        );
      }
      // The claim phases must not run: this mode exists to be cheap and safe.
      if (claims.some((c) => c.id !== 'C32')) {
        failures.push(
          `--residue ran claims other than C32: ${claims.map((c) => c.id).join(', ')}`,
        );
      }
      // The narrowing goes on the WIRE, not just in the client — a project with
      // 40k issues must not be paged in full to find three.
      const jql = requests.filter((r) => r.path === '/rest/api/3/search/jql');
      if (!jql.some((r) => /summary\s*~/.test(String(r.body?.jql)))) {
        failures.push('the inventory paged the project instead of narrowing in JQL');
      }
      return failures;
    },
  },
  {
    id: 'I',
    title: 'the documented cleanup command clears what it can',
    // The exact command the driver prints in its own residue table. If this
    // pass regresses, the runbook is telling the owner to type something that
    // does not work.
    pre: [['--write', '--keep']],
    args: ['--residue', '--purge', '--irreversible'],
    expectExit: EXIT_OK,
    check: ({ requests, claims, stderr, state }) => {
      const failures = [];
      const c33 = claims.find((c) => c.id === 'C33');
      if (c33 === undefined) failures.push('C33 did not run — nothing was purged');
      else if (c33.status !== 'PASS') failures.push(`C33 is ${c33.status}: ${c33.note}`);
      const deleted = requests.filter(
        (r) => r.method === 'DELETE' && /^\/rest\/api\/3\/issue\/[^/]+$/.test(r.path),
      );
      // Two, not one: the link claim (C39) needs a far end, and `--keep` left
      // both throwaway issues on the site for the purge to find.
      if (deleted.length !== 2) {
        failures.push(`expected 2 issue DELETEs, saw ${String(deleted.length)}`);
      }
      const alive = [...state.issues.values()].filter(
        (issue) => !issue.deleted && /^gate-c verify-live /.test(String(issue.summary)),
      );
      if (alive.length > 0) {
        failures.push(`${String(alive.length)} gate-c issue(s) survived the purge`);
      }
      // C32 runs BEFORE the purge, so its note is the inventory that the purge
      // then acted on — two issues and one staged file.
      failures.push(
        ...residueChecks(
          { claims, stderr },
          { issues: 2, versions: 1, components: 1, sprints: 1, media: 1 },
        ),
      );
      // The table printed at the end is the post-purge truth: what it could
      // clear is gone, and what it CANNOT clear is still named, or the operator
      // will believe the site is clean when a version, a sprint and a component
      // are still on it.
      for (const line of [
        'throwaway issues: none',
        'local files in JIRA_MEDIA_DIR: none',
      ]) {
        if (!stderr.includes(line)) {
          failures.push(`after the purge the table should say "${line}"`);
        }
      }
      for (const marker of [
        'Project settings → Releases',
        'Backlog → the sprint',
        'Project settings → Components',
      ]) {
        if (!stderr.includes(marker)) {
          failures.push(`the residue table stopped saying how to remove: ${marker}`);
        }
      }
      return failures;
    },
  },
  {
    id: 'J',
    title: 'a write with no --confirm-site never starts',
    args: ['--write', '--irreversible'],
    confirm: false,
    expectExit: EXIT_CONFIG,
    check: ({ requests, claims, stderr }) => {
      const failures = [];
      // The whole value of the guard is that it fires BEFORE the network.
      if (requests.length > 0) {
        failures.push(
          `${String(requests.length)} request(s) reached the fake despite the refusal`,
        );
      }
      if (claims.length > 0) failures.push('claims ran despite the refusal');
      if (!/--confirm-site/.test(stderr)) {
        failures.push('the refusal does not tell the operator what to type');
      }
      if (!stderr.includes(API_HOST)) {
        failures.push('the refusal does not name the site it would have mutated');
      }
      return failures;
    },
  },
  {
    id: 'K',
    title: 'a write confirming the WRONG site never starts',
    args: ['--write'],
    // The failure this exists for: a shell that still has last month's site
    // exported, and an operator who pasted the right host from the runbook.
    confirm: 'production.example.invalid',
    expectExit: EXIT_CONFIG,
    check: ({ requests, stderr }) => {
      const failures = [];
      if (requests.length > 0) {
        failures.push(`${String(requests.length)} request(s) reached the fake`);
      }
      if (!stderr.includes('production.example.invalid') || !stderr.includes(API_HOST)) {
        failures.push('the mismatch message does not name BOTH hosts');
      }
      return failures;
    },
  },
];

// ---------------------------------------------------------------------------
// Report parsing
// ---------------------------------------------------------------------------

const CLAIM_LINE = /^\s+(PASS|FAIL|SKIP)\s+(C\d\d)\s+(.*)$/;

/** @returns {{ id: string, status: string, title: string, note: string }[]} */
function parseClaims(stdout) {
  const rows = [];
  for (const line of stdout.split('\n')) {
    const match = CLAIM_LINE.exec(line);
    if (match === null) continue;
    const [, status, id, rest] = match;
    const split = rest.indexOf('  — ');
    rows.push({
      id,
      status,
      title: (split < 0 ? rest : rest.slice(0, split)).trim(),
      note: split < 0 ? '' : rest.slice(split + 4).trim(),
    });
  }
  return rows;
}

// ---------------------------------------------------------------------------
// Running one pass
// ---------------------------------------------------------------------------

/** The flags the driver refuses to honour without `--confirm-site` (CC-83). */
const DESTRUCTIVE_FLAGS = ['--write', '--irreversible', '--purge'];

/**
 * Build one driver invocation.
 *
 * `--confirm-site` is added for a destructive pass rather than written into
 * every pass's args, so that passes J and K — the ones that assert the guard
 * FIRES — are the only places the value is spelled out, and a future pass cannot
 * accidentally look confirmed because someone copied a flag list.
 */
function argvFor(pass, args, recordDir) {
  const needsConfirm = args.some((arg) => DESTRUCTIVE_FLAGS.includes(arg));
  const confirm =
    pass.confirm === false || !needsConfirm
      ? []
      : ['--confirm-site', typeof pass.confirm === 'string' ? pass.confirm : API_HOST];
  return [
    DRIVER,
    '--project',
    PROJECT,
    '--project2',
    PROJECT2,
    ...args,
    ...confirm,
    ...(recordDir === undefined ? [] : ['--record', recordDir]),
  ];
}

/**
 * @param {Pass} pass
 * @param {object} context
 * @returns {Promise<{ pass: Pass, exitCode: number, claims: object[], failures: string[], stdout: string, stderr: string }>}
 */
async function runPass(pass, context) {
  const fake = await startFakeJira({
    email: EMAIL,
    token: TOKEN,
    projectKey: PROJECT,
    project2Key: PROJECT2,
    certDir: context.certDir,
    ...(pass.fake ?? {}),
  });

  try {
    for (const fault of pass.faults ?? []) fake.arm(fault);

    const recordDir = join(context.workdir, `record-${pass.id}`);
    const args = argvFor(pass, pass.args, pass.record === true ? recordDir : undefined);

    const env = {
      ...process.env,
      JIRA_SITE: fake.origin,
      JIRA_EMAIL: EMAIL,
      JIRA_API_TOKEN: TOKEN,
      JIRA_ALLOWED_HOSTS: `${API_HOST},${MEDIA_HOST}`,
      JIRA_MEDIA_DIR: join(context.workdir, `media-${pass.id}`),
      NODE_EXTRA_CA_CERTS: fake.certFile,
      NODE_OPTIONS: [process.env['NODE_OPTIONS'], `--import ${context.preloadUrl}`]
        .filter((value) => value !== undefined && value !== '')
        .join(' '),
    };
    await mkdir(env.JIRA_MEDIA_DIR, { recursive: true });

    const failures = [];
    // Set-up runs, if the pass needs a site that is already dirty. Their traffic
    // is dropped afterwards so `check` only ever reasons about the measured run.
    for (const preArgs of pass.pre ?? []) {
      const pre = await spawnDriver(argvFor(pass, preArgs), env, context.verbose);
      if (pre.exitCode !== EXIT_OK) {
        failures.push(
          `set-up run \`${preArgs.join(' ')}\` exited ${String(pre.exitCode)}, ` +
            'so the pass never reached what it meant to test',
        );
      }
      fake.clearRequests();
    }

    const result = await spawnDriver(args, env, context.verbose);
    const claims = parseClaims(result.stdout);

    if (pass.expectExit !== undefined && result.exitCode !== pass.expectExit) {
      failures.push(
        `exit code ${String(result.exitCode)}, expected ${String(pass.expectExit)}`,
      );
    }
    // `state` is the fake's own view of the world after the run — the only way
    // to assert an EFFECT (the sprint really is closed) rather than an intent.
    const context_ = {
      requests: fake.requests,
      claims,
      recordDir,
      state: fake.state,
      stdout: result.stdout,
      stderr: result.stderr,
    };
    failures.push(...universalChecks(context_));
    failures.push(...(pass.check?.(context_) ?? []));

    return {
      pass,
      exitCode: result.exitCode,
      claims,
      failures,
      stdout: result.stdout,
      stderr: result.stderr,
      requests: fake.requests.slice(),
      accountIds: fake.state.users.map((user) => user.accountId),
      recordDir: pass.record === true ? recordDir : undefined,
      dump: context.dump === true,
    };
  } finally {
    await fake.close();
  }
}

/** @returns {Promise<{ exitCode: number, stdout: string, stderr: string }>} */
function spawnDriver(args, env, verbose) {
  return new Promise((resolvePromise, rejectPromise) => {
    const child = spawn(process.execPath, args, {
      cwd: REPO_ROOT,
      env,
      stdio: ['ignore', 'pipe', 'pipe'],
    });
    let stdout = '';
    let stderr = '';
    child.stdout.setEncoding('utf8');
    child.stderr.setEncoding('utf8');
    child.stdout.on('data', (chunk) => {
      stdout += chunk;
      if (verbose) process.stdout.write(chunk);
    });
    child.stderr.on('data', (chunk) => {
      stderr += chunk;
      if (verbose) process.stderr.write(chunk);
    });
    const timer = setTimeout(() => {
      child.kill('SIGKILL');
      rejectPromise(new Error(`the driver did not finish within ${PASS_TIMEOUT_MS} ms`));
    }, PASS_TIMEOUT_MS);
    child.on('error', (error) => {
      clearTimeout(timer);
      rejectPromise(error);
    });
    child.on('close', (code) => {
      clearTimeout(timer);
      resolvePromise({ exitCode: code ?? 1, stdout, stderr });
    });
  });
}

// ---------------------------------------------------------------------------
// Redaction audit
// ---------------------------------------------------------------------------

/**
 * The driver's `--record` output is the artefact the owner attaches to the gate,
 * so its redactor is a security control, not a nicety. Grep the capture for
 * every secret the fake knows about. Anything that survives is a leak the live
 * run would have written to disk with a REAL token and REAL accountIds in it.
 */
async function auditRecording(dir, accountIds) {
  if (dir === undefined) return [];
  if (!existsSync(dir)) return [`--record wrote nothing to ${dir}`];
  const files = await readdir(dir);
  if (files.length === 0) return [`--record left ${dir} empty`];
  const secrets = [
    ['the API token', TOKEN],
    ['the account email', EMAIL],
    ['the site hostname', API_HOST],
    ...accountIds.map((id, index) => [`accountId #${String(index + 1)} (${id})`, id]),
  ];
  const failures = [];
  for (const name of files) {
    const text = await readFile(join(dir, name), 'utf8');
    for (const [label, secret] of secrets) {
      if (secret !== undefined && secret !== '' && text.includes(secret)) {
        failures.push(`${name} leaks ${label}`);
      }
    }
  }
  return [...new Set(failures)];
}

// ---------------------------------------------------------------------------
// Entry
// ---------------------------------------------------------------------------

async function main() {
  const { values } = parseArgs({
    args: process.argv.slice(2),
    options: {
      pass: { type: 'string', multiple: true },
      dump: { type: 'boolean', default: false },
      keep: { type: 'boolean', default: false },
      verbose: { type: 'boolean', default: false },
      help: { type: 'boolean', default: false },
    },
    strict: true,
  });

  if (values.help === true) {
    process.stdout.write(
      'rehearse-live — run scripts/verify-live.mjs against scripts/fake-jira.mjs.\n\n' +
        'Flags: --pass <A..K> (repeatable), --dump, --keep, --verbose, --help\n',
    );
    return EXIT_OK;
  }

  if (!existsSync(SERVER_ENTRY)) {
    process.stderr.write(`no build at ${SERVER_ENTRY} — run \`npm run build\` first.\n`);
    return EXIT_CONFIG;
  }

  const selected =
    values.pass === undefined
      ? PASSES
      : PASSES.filter((pass) => values.pass.includes(pass.id));
  if (selected.length === 0) {
    process.stderr.write(`no pass matched ${String(values.pass)}\n`);
    return EXIT_CONFIG;
  }

  const workdir = await mkdtemp(join(tmpdir(), 'rehearse-live-'));
  const certDir = join(workdir, 'tls');
  const preload = join(workdir, 'rehearsal-dns.mjs');
  await mkdir(certDir, { recursive: true });
  await writeFile(preload, PRELOAD_SOURCE, 'utf8');

  const context = {
    workdir,
    certDir,
    preloadUrl: pathToFileURL(preload).href,
    verbose: values.verbose === true,
    dump: values.dump === true,
  };

  const results = [];
  try {
    for (const pass of selected) {
      process.stdout.write(`\n=== pass ${pass.id}: ${pass.title}\n`);
      const result = await runPass(pass, context);
      if (result.recordDir !== undefined) {
        result.failures.push(
          ...(await auditRecording(result.recordDir, result.accountIds)),
        );
      }
      results.push(result);
      report(result);
    }
  } finally {
    if (values.keep === true) {
      process.stdout.write(`\nworkdir kept: ${workdir}\n`);
    } else {
      await rm(workdir, { recursive: true, force: true });
    }
  }

  return summarise(results);
}

function report(result) {
  const counts = { PASS: 0, FAIL: 0, SKIP: 0 };
  for (const claim of result.claims) counts[claim.status] += 1;
  process.stdout.write(
    `    ${String(counts.PASS)} passed, ${String(counts.FAIL)} failed, ` +
      `${String(counts.SKIP)} skipped, exit ${String(result.exitCode)}\n`,
  );
  for (const claim of result.claims) {
    if (claim.status === 'PASS') continue;
    process.stdout.write(
      `    ${claim.status}  ${claim.id}  ${claim.title}` +
        (claim.note === '' ? '' : `  — ${claim.note}`) +
        '\n',
    );
  }
  for (const failure of result.failures) {
    process.stdout.write(`    REHEARSAL FAILURE  ${failure}\n`);
  }
  if (result.dump === true) {
    for (const request of result.requests) {
      const query = new URLSearchParams(request.query).toString();
      process.stdout.write(
        `    ${String(request.status ?? '---')} ${request.method} ${request.path}` +
          `${query === '' ? '' : `?${query}`}` +
          `${request.onMediaHost ? '  [media host]' : ''}` +
          `${request.hasAuthorization ? '' : '  [no auth]'}\n`,
      );
    }
  }
}

function summarise(results) {
  process.stdout.write('\n=== rehearsal summary\n');
  let bad = 0;
  for (const result of results) {
    const ok = result.failures.length === 0;
    if (!ok) bad += 1;
    process.stdout.write(
      `  ${ok ? 'ok  ' : 'BAD '} pass ${result.pass.id}  ${result.pass.title}\n`,
    );
  }
  if (bad === 0) {
    process.stdout.write(
      '\nThe driver behaved. This says nothing about whether Jira agrees —\n' +
        'see docs/RELEASING.md §6 for what still needs a real tenant.\n',
    );
    return EXIT_OK;
  }
  process.stdout.write(`\n${String(bad)} pass(es) regressed.\n`);
  return EXIT_FAILURE;
}

main()
  .then((code) => {
    process.exitCode = code;
  })
  .catch((error) => {
    process.stderr.write(`rehearse-live failed: ${String(error?.stack ?? error)}\n`);
    process.exitCode = EXIT_CONFIG;
  });
